library(mirai.promises)
library(mirai)
library(promises)
nanotest <- function(x) invisible(x || stop("is not TRUE when expected to be TRUE"))
daemons(n = 1L, dispatcher = FALSE)
nanotest(is.promise(p1 <- as.promise(mirai("completed"))))
nanotest(is.promise(p2 <- as.promise(mirai(mirai::mirai()))))
nanotest(is.promise(p3 <- mirai("completed") %...>% identity()))
daemons(0L)
Sys.sleep(1L)
