library(mirai.promises)
nanotest <- function(x) invisible(x || stop("is not TRUE when expected to be TRUE"))
nanotest(is.promise(p1 <- as.promise(mirai("completed"))))
nanotest(is.promise(p2 <- mirai("completed") %...>% identity()))
nanotest(mirai.promises:::..[["freq"]] == 0.1)
nanotest(is.null(polling(freq = 1000)))
nanotest(mirai.promises:::..[["freq"]] == 1L)
nanotest(is.null(polling()))
nanotest(mirai.promises:::..[["freq"]] == 0.1)
Sys.sleep(3L)
